// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "src/internal/racket/dto"

	mock "github.com/stretchr/testify/mock"

	model "src/internal/racket/model"
)

// IRacketRepository is an autogenerated mock type for the IRacketRepository type
type IRacketRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, Racket
func (_m *IRacketRepository) Create(ctx context.Context, Racket *model.Racket) error {
	ret := _m.Called(ctx, Racket)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Racket) error); ok {
		r0 = rf(ctx, Racket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRacketByID provides a mock function with given fields: ctx, id
func (_m *IRacketRepository) GetRacketByID(ctx context.Context, id string) (*model.Racket, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRacketByID")
	}

	var r0 *model.Racket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Racket, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Racket); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Racket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRackets provides a mock function with given fields: ctx, req
func (_m *IRacketRepository) ListRackets(ctx context.Context, req *dto.ListRacketReq) ([]*model.Racket, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListRackets")
	}

	var r0 []*model.Racket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListRacketReq) ([]*model.Racket, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListRacketReq) []*model.Racket); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Racket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.ListRacketReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, Racket
func (_m *IRacketRepository) Update(ctx context.Context, Racket *model.Racket) error {
	ret := _m.Called(ctx, Racket)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Racket) error); ok {
		r0 = rf(ctx, Racket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIRacketRepository creates a new instance of IRacketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRacketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRacketRepository {
	mock := &IRacketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
