drop table if exists "user" cascade;
drop table if exists cart cascade;
drop table if exists "order" cascade;
drop table if exists racket cascade;
drop table if exists cart_racket cascade;
drop table if exists order_racket cascade;
drop table if exists feedback cascade;
drop table if exists supplier cascade;
drop table if exists delivery cascade;